# Generated by Django 4.2.4 on 2023-09-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifnine_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='authentic_rating',
            field=models.CharField(blank=True, default='100', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='chat_resp_time',
            field=models.CharField(blank=True, default='100', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_on_time',
            field=models.CharField(blank=True, default='100', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='warranty_period',
            field=models.CharField(blank=True, default='100', max_length=30, null=True),
        ),
    ]
