# Generated by Django 4.2.4 on 2023-09-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifnine_core', '0006_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
