# Generated by Django 4.2.4 on 2023-09-14 10:56

from django.db import migrations, models
import ifnine_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('ifnine_core', '0007_vendor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor.png', upload_to=ifnine_core.models.user_directory_path),
        ),
    ]
