# Generated by Django 4.2.4 on 2023-09-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifnine_core', '0009_alter_productimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='product.png', upload_to='product_images'),
        ),
    ]
