# Generated by Django 4.2.4 on 2023-09-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifnine_core', '0011_alter_productimages_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='images',
        ),
    ]
