# Generated by Django 4.2.4 on 2023-09-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifnine_core', '0012_rename_image_productimages_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mfd_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
