# Generated by Django 4.2.4 on 2023-09-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifnine_core', '0017_alter_productreview_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOrderItems',
            new_name='CartOrderProducts',
        ),
    ]
