# Generated by Django 4.2.4 on 2023-09-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifnine_core', '0018_rename_cartorderitems_cartorderproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
    ]
