# Generated by Django 4.2.4 on 2023-09-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifnine_core', '0019_address_mobile_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
    ]
