# Generated by Django 4.2.4 on 2023-09-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifnine_core', '0020_address_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
